### ISSUE TITLE
No Module named support

### ISSUE THREAD

**Issue by SaibotMagd** [carlohamalainen/volgenmodel-nipype#3]
Hi, 
I try to generate a template for a new atlas, I'm creating but I'm struggle with the whole volgenmodel-nipype install process. After solving a lot of issues I don't know what do to with this one:

```
210719-09:31:20,327 workflow ERROR:
	 ['Node initial_model_fwhm3d failed to run on host nib03.']
210719-09:31:20,328 workflow INFO:
	 Saving crash info to /home/toolboxes/volgenmodel-nipype/crash-20210719-093120-tgottsch-initial_model_fwhm3d-fe5994dd-f242-43f9-99ad-eafb10c1d34f.pklz
210719-09:31:20,328 workflow INFO:
	 Traceback (most recent call last):
  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 267, in _send_procs_to_workers
    jobid].hash_exists()
  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 260, in hash_exists
    hashed_inputs, hashvalue = self._get_hashval()
  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 429, in _get_hashval
    self._get_inputs()
  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 472, in _get_inputs
    results = loadpkl(results_file)
  File "/home/anaconda3/envs/py27/lib/python2.7/site-packages/nipype/utils/filemanip.py", line 445, in loadpkl
    return pickle.load(pkl_file)
  File "/home/anaconda3/envs/py27/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/anaconda3/envs/py27/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/anaconda3/envs/py27/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/home/anaconda3/envs/py27/lib/python2.7/pickle.py", line 1130, in find_class
    __import__(module)
ImportError: No module named support
```

**Comment by carlohamalainen** [comment]
I've never tested volgenmodel with Anaconda, only vanilla Debian/Ubuntu distributions with the system Python.

Does a simple nipype program run?

**Comment by SaibotMagd** [comment]
I tried the examples from https://nipype.readthedocs.io/en/latest/users/examples/workshop_dartmouth_2010.html and it doesn't work. I have to use conda because it runs on a server without admin rights, so I can't run an old python 2 environment.  

I also tried to use the docker file but it's also broken because one url for the superbuild of GSL is down. But I  tried a VM with Ubuntu 20 and a complete virgin Ubuntu 20 system with admin rights only to use the install commands you provided. Nothing works till now. So if you could find an easy way to install it, I would love to know about. I'm building a brain atlas for my masterthesis and so I need a proper template and I hoped the volgenmodel-pipeline could help.

I think I still couldn't find the right versions of all the necessary packages because a lot of them seems to be pretty old. It seems like I need minc-tools <2.0, networkx <=1.11, nipyse < 2.0, pydicom <=1.4 and the widgets from git://github.com/BIC-MNI/minc-toolkit.git .

conda package list:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
atk-1.0                   2.36.0               h3371d22_4    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                        py_1    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.7.5             h06a4308_1  
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2020.6.20          pyhd3eb1b0_3  
click                     7.1.2              pyh9f0ad1d_0    conda-forge
configparser              3.7.3            py27h8c360ce_2    conda-forge
curl                      7.61.0               h84994c4_0  
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               h48d8840_2    conda-forge
decorator                 4.4.2              pyhd3eb1b0_0  
expat                     2.4.1                h9c3ff4c_0    conda-forge
flex                      2.6.4                ha10e3a4_1  
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
future                    0.18.2           py27h8c360ce_1    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.68.3               h9c3ff4c_0    conda-forge
glib-tools                2.68.3               h9c3ff4c_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.4               hb53b477_0  
gtk2                      2.24.33              hab0c2f8_0    conda-forge
h5py                      2.8.0            py27h39dcb92_0  
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.8.18               h6792536_1  
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
keepalive                 0.5                        py_1    conda-forge
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.61.0               h1ad7b7a_0  
libdeflate                1.7                  h7f98852_5    conda-forge
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               h14aa051_19    conda-forge
libgfortran4              7.5.0               h14aa051_19    conda-forge
libglib                   2.68.3               h3e27bee_0    conda-forge
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libminc                   2.3.00               hd28b015_0    hcc
libnetcdf                 4.5.0                h569e9f1_7  
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
libxslt                   1.1.32            hae48121_1003    conda-forge
linecache2                1.0.0                      py_1    conda-forge
lxml                      4.4.1            py27h7ec2d77_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
m4                        1.4.18               h4e445db_0  
matplotlib                2.2.3            py27h8a2030e_1    conda-forge
matplotlib-base           2.2.3            py27h60b886d_1    conda-forge
minc-tools                2.3.00               hd28b015_0    hcc
mock                      3.0.5            py27h8c360ce_1    conda-forge
more-itertools            5.0.0                      py_0    conda-forge
ncurses                   6.2                  he6710b0_1  
networkx                  1.11                     py27_1  
nibabel                   2.5.1                      py_0    conda-forge
nipype                    0.14.0                   py27_1    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openssl                   1.0.2u               h516909a_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pip                       19.3.1                   py27_0  
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.11.0                     py_0    conda-forge
prov                      1.5.0                    py27_0    conda-forge
psutil                    5.7.0            py27hdf8410d_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pydicom                   2.1.2              pyhd3deb0d_0    conda-forge
pydotplus                 2.0.2                      py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.6.0           py27h13b7fb3_1008    conda-forge
pytest                    4.5.0                    py27_0    conda-forge
python                    2.7.18               ha1903f6_2  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
qt                        5.6.2             hf516382_1011    conda-forge
rdflib                    4.2.2                 py27_1000    conda-forge
readline                  8.1                  h27cfd23_0  
scandir                   1.10.0           py27hdf8410d_1    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0  
simplejson                3.17.0           py27hdf8410d_1    conda-forge
singledispatch            3.6.1              pyh44b312d_0    conda-forge
sip                       4.18.1          py27hf484d3e_1000    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sparqlwrapper             1.8.5           py27h8c360ce_1002    conda-forge
sqlite                    3.36.0               hc218d9a_0  
subprocess32              3.5.4            py27h516909a_0    conda-forge
tk                        8.6.10               hbc83047_0  
tornado                   5.1.1           py27h14c3975_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
traits                    5.2.0            py27h516909a_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0  
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xvfbwrapper               0.2.9                 py27_1001    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.5.0                ha95c52a_0    conda-forge

**Comment by SaibotMagd** [comment]
I installed all old versions I could identify (see previous posting) and it runs a little bit further. For me it seems like a classical enviromental-path issue:

```
210722-14:18:02,621 interface WARNING:
	 Could not get linked libraries for "mincnorm".
Traceback (most recent call last):
  File "/home/toolboxes/volgenmodel-nipype/volgenmodel.py", line 856, in <module>
    workflow.run(plugin='MultiProc', plugin_args={'n_procs' : 4})
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 592, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 161, in run
    result=result))
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 218, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 51, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 407, in run
    self._run_interface()
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 517, in _run_interface
    self._result = self._run_command(execute)
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run()
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1089, in run
    runtime = self._run_interface(runtime)
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1696, in _run_interface
    self.raise_exception(runtime)
  File "/home/anaconda3/envs/py27newni/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1639, in raise_exception
    **runtime.dictcopy()))
RuntimeError: Command:
mincnorm -clamp -clobber -cutoff 0.1 -threshold_mask mouse00_volcentre_norm_threshold_mask.mnc -threshold -threshold_blur 7.5 -threshold_perc 0.1 /home/toolboxes/volgenmodel-nipype/volgenmodel-fast-example/workflow/preprocess_volcentre/mapflow/_preprocess_volcentre0/mouse00_volcentre.mnc mouse00_volcentre_norm.mnc
Standard output:
*** getting lower range of /home/toolboxes/volgenmodel-nipype/volgenmodel-fast-example/workflow/preprocess_volcentre/mapflow/_preprocess_volcentre0/mouse00_volcentre.mnc [0.1]
*** getting upper range of /home/toolboxes/volgenmodel-nipype/volgenmodel-fast-example/workflow/preprocess_volcentre/mapflow/_preprocess_volcentre0/mouse00_volcentre.mnc [99.9]
*** scaling /home/toolboxes/volgenmodel-nipype/volgenmodel-fast-example/workflow/preprocess_volcentre/mapflow/_preprocess_volcentre0/mouse00_volcentre.mnc in range [0.03258681223:99.15318352]
*** outputting in the range  [0:100]
Processing:.................................................................................................Done
Processing:.................................................................................................Done
Standard error:
Can't exec "mincblur": No such file or directory at /home/anaconda3/envs/py27newni/bin/mincnorm line 222.
Died at /home/anaconda3/envs/py27newni/bin/mincnorm line 222.
Return code: 2
```

Even if I work with linux for nearly a year the difficulty to solve such a problem is way to high. So I should set the paths right but how and where? The install scripts from minc-tools: `minc-toolkit-config.unix.sh.cmake` seems to do nothing.

**Comment by carlohamalainen** [comment]
Your MINC installation is broken.

I had a look at the [CAI fork](https://github.com/CAIsr/volgenmodel-nipype) and they have done a lot of work including upgrading to Python3.

I merged their fork today and now the installation process is much simpler on Ubuntu 20 (see the updated README). They also have instructions for conda and Windows Linux Subsystem but I have not used these.

**Comment by SaibotMagd** [comment]
> Your MINC installation is broken.
> 
> I had a look at the [CAI fork](https://github.com/CAIsr/volgenmodel-nipype) and they have done a lot of work including upgrading to Python3.
> 
> I merged their fork today and now the installation process is much simpler on Ubuntu 20 (see the updated README). They also have instructions for conda and Windows Linux Subsystem but I have not used these.

This sounds great. Thanks a lot!

**Comment by SaibotMagd** [comment]
I runs further but now there's the next problem: mincblur , I think this is part of minc-toolkit v2 (https://github.com/BIC-MNI/minc-toolkit-v2) but also mandatory for the volgenmodel.
